### ISSUE TITLE
DSP.js FFT issues

### ISSUE THREAD

**Issue by echo66** [echo66/PhaseVocoderJS#3]
It seems that the error between MATLAB STFT and DSP.js Windowing + FFT is higher than it should. There are indexes that change phase signs.

**Comment by echo66** [comment]
Examples:

 ***\* Issue at index 971 at frame 22 ****
 my value:   -0.1943424508
 test value: 0.0028793388046324253
 WRONG SIGN

 ***\* Issue at index 979 at frame 22 ****
 my value:   3.101530522
 test value: -3.1335537433624268
 WRONG SIGN

 ***\* Issue at index 1009 at frame 23 ****
my value:   3.079066476
test value: -3.1021502017974854
WRONG SIGN

**Comment by echo66** [comment]
Just open an issue in dsp.js repository and close this issue.

**Comment by j-funk** [comment]
@echo66 is this with the main FFT algorithm in dsp,js, or with the RFFT algorithm?
